### ISSUE TITLE
get result

### ISSUE THREAD

**Issue by darongE** [fvlasie/dbpediaPlaceData#1]
I forgot to install JSON.pm on MAC
https://stackoverflow.com/questions/50318148/cant-install-json-pm
Try curl and get some result .. Sorry misunderstand meaning.
```
yoshimi~/Music/cridb/dbpediaPlaceData$ curl -s "http://dbpedia.org/data/Haeinsa.json"
 | perl dbpediaPlaceData.txt 'Haeinsa'

  "command": "save",
  "record_type": "thing",
  "data": {
    "lat": 35.7999992370605,
    "subtype": "place",
    "name": "Haeinsa",
    "long": 128.100006103516,
    "notes": "wkpd-Haeinsa"
  }
```

**Comment by fvlasie** [comment]
네

**Comment by fvlasie** [comment]
좋아요?

**Comment by darongE** [comment]
I'm making example program to read curl and perl command program.
If command can read on QProcess, It's easy to manage JSON data.
I asked [stackoverflow](https://stackoverflow.com/questions/51750422/send-command-to-server-using-qprocess). 🐈

**Comment by fvlasie** [comment]
알았어요
